- hosts: docker
  connection: local
  become: yes
  tags:
    - raspap
  roles:
    - setup
    - defaults
    - lighttp
    - dhcpcd
    - dnsmasq
    - openvpn
    - hostapd
    - wpasupplicant
    - raspapd

