- hosts: raspberrypis
  become: yes
  tags:
    - raspap
  roles:
    - setup
    - defaults
    - lighttp
    - dhcpcd
    - dnsmasq
    - openvpn
    - network
    - hostapd
    - wpasupplicant
    - raspapd
