- name: wpasupplicant config exists
  stat:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    register: wpasupplicant_exists

- name: wpasupplicant set country code
  lineinfile:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    regexp: "^country="
    line: country={{ hostapd_country_code }}
  when: wpasupplicant_exists.stat.exists == true

