---
- name: Install dependencies
  apt:
    state: present
    update_cache: yes
    name:
      - lighttpd
      - dnsmasq
      - hostapd
      - iptables-persistent
      - vnstat
      - qrencode
      - openvpn
      - wireless-tools
      - iw
      - dhcpcd5
      - wpasupplicant

- name: Install php-cgi (debian 10)
  apt:
    state: present
    name:
      - php7.3-cgi
  when: ansible_distribution == "Debian" and ansible_distribution_version == "10"

- name: Install php-cgi (debian 11)
  apt:
    state: present
    name:
      - php7.4-cgi
  when: ansible_distribution != "Debian" and ansible_distribution_version != "10"

- name: Remove html directory
  file:
    path: /var/www/html
    state: absent

- name: Clone RaspAP project in html directory
  git:
    repo: https://github.com/RaspAP/raspap-webgui
    dest: /var/www/html

- name: Change html permissions to www-data
  file:
    path: /var/www/html
    owner: www-data
    group: www-data

- name: Copy www-data sudoers rules
  copy:
    src: /var/www/html/installers/raspap.sudoers
    dest: /etc/sudoers.d/090_raspap
    remote_src: yes

- name: Create RaspAP configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
  loop:
    - /etc/raspap
    - /etc/raspap/backups
    - /etc/raspap/networking
    - /etc/raspap/hostapd
    - /etc/raspap/lighttpd
    - /etc/raspap/openvpn
